### ISSUE TITLE
MDT heading can't be neither created nor updated on dev and showcase boxes

### ISSUE THREAD

**Issue by anna-otrokhova** [RippleOSI/Ripple-Qewd#66]
We have checked and figured out that, MDT doesn't work as well both creation and editing. Let me prepare the screen:
PUT: https://prnt.sc/hiwf1k
log: https://prnt.sc/hiwew1
POST: https://prnt.sc/hiw7qk

Related issue: https://github.com/PulseTile/PulseTile-React/issues/74
https://github.com/PulseTile/PulseTile/issues/61

**Comment by robtweed** [comment]
The problem is that the POST/PUT information was not originally available for MDT Reports, so it's not currently supported.  Ian has provided the info needed at https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/MDT/mdt_report_1.1.0.md

However, I need to know how the Flat JSON values shown here:

"mdt_output_report/referral_details/mdt_referral/request:0/service_name": "MDT referral",
  "mdt_output_report/referral_details/mdt_referral/request:0/timing": "R2/2016-12-19T18:00:00Z/P2M",
  "mdt_output_report/referral_details/mdt_referral/narrative": "MDT request",
  "mdt_output_report/referral_details/mdt_referral/service_team": "MDT Prostate Cancer team",
  "mdt_output_report/referral_details/referral_requested/ism_transition/current_state|code": "526",
  "mdt_output_report/referral_details/referral_requested/ism_transition/careflow_step|code": "at0026",
  "mdt_output_report/referral_details/referral_requested/service_requested": "MDT Referral",
  "mdt_output_report/referral_details/referral_requested/time": "2016-12-19T18:03:13.395Z",
  "mdt_output_report/history/question_to_mdt/question_to_mdt": "Increasing back pain",
  "mdt_output_report/plan_and_requested_actions/recommendation/meeting_discussion": "Investigations normal. Review in 3 weeks"

..line up with the request values sent from PulseTile, ie:

serviceTeam
dateOfRequest
dateOfMeeting
timeOfMeeting (currently missing in PulseTile request by the way)
question
notes

Need some help on that please.

Also Ian/Tony - I see that the AQL retrieves careflow_step and Service_team,  but I don't see these used in the UI

**Comment by anna-otrokhova** [comment]
It works now. Thank you.

**Comment by anna-otrokhova** [comment]
I will close it after checking on Angular.

**Comment by anna-otrokhova** [comment]
The issue is still present on showcase box.
@robtweed 
Rob, could you move the changes there as well?

**Comment by robtweed** [comment]
Should be on showcase now also

**Comment by anna-otrokhova** [comment]
It works. Thank you
